name: Update Site

on: [push, workflow_dispatch,]

jobs:
    build:
      runs-on: ubuntu-latest
  
      steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
            fetch-depth: 0
            ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
            persist-credentials: false
        
      - name: NPM install 
        run: | 
            npm i
      
      - name: Run Deployment
        run: |
            git config --global user.email "actions@github.com"
            git config --global user.name "GitHub Actions"
            npm run deploy
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}